### ISSUE TITLE
Call to save.php fails with client error

### ISSUE THREAD

**Issue by leNicDev** [instawallet/weaveid-js#1]
Hi, I just tried to integrate weaveid-js into an Angular 11 app and I noticed two things:
-  Vue seems to be initialized in dev mode when `openLoginModal` is called
- After clicking on "Sign in", weaveid-js throws this error:
```
Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at login.html:462
```
When debugging the script, this seems to be root of the error:
[https://i.imgur.com/OFzwqRC.png](https://i.imgur.com/OFzwqRC.png)

The POST request to https://weaveid.io/arweave/save.php succeeded with status 200 but the response body was empty.

You can find a minimal reproduction here:
https://angular-ivy-9c6ngb.stackblitz.io/

And here's the source code:
https://stackblitz.com/edit/angular-ivy-9c6ngb?file=src%2Fapp%2Fapp.component.ts

Thanks a lot for your help!

**Comment by instawallet** [comment]
Hey @leNicDev Thanks for reporting this! I went ahead and fixed the account creation bug you reported. It was as simple as setting the `fetch()` mode to "cors": https://github.com/instawallet/weaveid/commit/affbc51d813e7ca46f0c414342b17260e666aeaa

Can we close this issue?

**Comment by leNicDev** [comment]
@instawallet How can I test this? The issue still remains.

**Comment by leNicDev** [comment]
Has been fixed. Thanks a lot!
